### ISSUE TITLE
Unable to build libs.

### ISSUE THREAD

**Issue by abishekh** [chzhong/serial-android#1]
I tried building the libs using the script 'build-libs.sh' and using ndk-build as well. 
I get the following error : 

```
abishek@abishek-ubuntu:~/Downloads/serial-android$ ./build-libs.sh 
[armeabi-v7a] SharedLibrary  : libserial.so
/home/abishek/Downloads/serial-android/libserial/src/main/jni/libs/serialport/glob.c:394: error: undefined reference to 'issetugid'
collect2: error: ld returned 1 exit status
make: *** [obj/local/armeabi-v7a/libserial.so] Error 1
```

**Comment by abishekh** [comment]
I think its an issue with using a higher NDK revision. Is there some sort of work around other than downgrading the NDK rev ?

**Comment by chzhong** [comment]
Hi @abishekh , what is `APP_PLATFORM` in your Application.mk? `issetugid` is not defined in `unistd.h` since android-21. You can try to change `APP_PLATFORM` to `android-16` to see whether this problem still exists, or your can define it by:
`extern int issetugid(void);`
This symbol exists in libc.so (or libc.a) in all platforms of my NDK.

You can check whether android-16 is in your NDK's platforms folder.

**Comment by chzhong** [comment]
I've downloaded NDK r13 and fixed build break on it (It works with NDK r10c and NDK r13) . @abishekh would you please try the latest code?

**Comment by abishekh** [comment]
Yes, thanks the updated code works with r13. I had initially tried it with r12 and it gave me the issetugid issue. Downgraded to r10a (as per your previous documentation)and it had an issue with `#include <sys/_types.h>` under glob.h . Took out the "_" and it built successfully with r10a. All good out of the box with r13 now.

**Comment by abishekh** [comment]
Just a side request, I think it would be great if the `PortInfo` constructor was `public` .
